
INSERT INTO USER (LOGIN, PASSWORD) VALUES ('dn100985pev', '123');
INSERT INTO USER (LOGIN, PASSWORD) VALUES ('it100985pev', '123');


INSERT INTO USER_SETTINGS (LOGIN, VALUE, DATE_EDIT) VALUES ('dn100985pev', 'default', CURRENT_TIMESTAMP());
INSERT INTO USER_SETTINGS (LOGIN, VALUE, DATE_EDIT) VALUES ('it100985pev', 'default', CURRENT_TIMESTAMP());